package alertSystem;

import javax.mail.*;
import javax.mail.internet.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

public class EmailAlert {

    private static final String EMAIL_FROM = "watchtower000@outlook.com";
    private static final String EMAIL_PASSWORD = "Watchtower1@";
    private static final String EMAIL_TO = "ai.expert21815@gmail.com";
    private static final String SMTP_SERVER = "smtp-mail.outlook.com";
    private static final int SMTP_PORT = 587;

    public static void sendEmailAlert(String filePath, String action) {
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", SMTP_SERVER);
        props.put("mail.smtp.port", SMTP_PORT);
        props.put("mail.smtp.ssl.trust", SMTP_SERVER);

        // Create a session
        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(EMAIL_FROM, EMAIL_PASSWORD);
            }
        });

        session.setDebug(true);  // Enable debugging to see email sending process

        try {
            // Create the email message
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(EMAIL_FROM));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(EMAIL_TO));

            // Email subject
            message.setSubject("ALERT: File " + action + " Detected!");

            // Format the current timestamp
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String timestamp = dateFormat.format(new Date());

            // Email body with detailed information
            String emailBody = "A file-related event occurred. Below are the details:\n\n" +
                    "Action: " + action + "\n\n" +
                    "File Path: " + filePath + "\n\n" +
                    "Timestamp: " + timestamp + "\n\n" +
                    "Please review the event for any necessary actions.\n\n" +
                    "Alert generated by WatchTower system.";

            // Set the email content
            message.setText(emailBody);

            // Send the message
            Transport.send(message);
            System.out.println("Email sent successfully with detailed information.");

        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }
}
